include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    unnecessary_null_checks: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    always_use_package_imports: true
    use_build_context_synchronously: true
    avoid_redundant_argument_values: true
    prefer_const_literals_to_create_immutables: true


