name: inkwise_pdf
description: A powerful PDF editor app built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # PDF tools
  pdf: ^3.10.4
  pdf_render: ^1.4.0
  pdfx: ^2.6.0
  # syncfusion_flutter_pdfviewer: ^30.2.5  # For text extraction only - requires Dart 3.7+
  cross_file: ^0.3.3
  # PDF editing packages
  image: ^4.1.3  # For image manipulation

  # OCR and permissions
  # flutter_tesseract_ocr: removed (switched to google_ml_kit)
  permission_handler: ^12.0.1

  # File handling
  file_picker: ^10.3.1
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  path: ^1.9.0

  # Local Analytics (replaces Firebase)
  # firebase_core: ^2.31.0
  # firebase_auth: ^4.17.4
  # firebase_analytics: ^10.10.4
  # firebase_crashlytics: ^3.5.4
  # google_sign_in: ^6.2.1

  # Image and sharing
  image_picker: ^1.0.7
  share_plus: ^11.1.0

  # UI and utilities
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  intl: ^0.20.2

  # AI and ML capabilities - using compatible versions
  # tflite_flutter: ^0.10.4  # Deprecated - replaced with modern alternatives
  # tflite_flutter_helper: ^0.3.1  # Deprecated - replaced with modern alternatives
  # ml_algo: ^16.17.6  # Modern ML algorithms library - requires Dart 3.6+
  # ml_dataframe: ^1.6.0  # Data manipulation for ML - requires Dart 3.6+
  # ml_preprocessing: ^7.0.0  # Data preprocessing for ML - requires Dart 3.6+

  # Translation and language processing (offline-first)
  # translator: ^0.1.7  # Commented out - using offline translation
  # language_detector: ^0.0.2  # Not used in current implementation

  # Voice and speech
  speech_to_text: ^6.3.0  # Compatible with Dart 3.5.4
  flutter_tts: ^3.8.5  # Compatible with Dart 3.5.4

  # Advanced image processing
  
  # image_editor_plus: ^0.1.6  # Not used in current implementation
  
  # Database and storage
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Encryption and security
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
  # Advanced UI components
  flutter_staggered_grid_view: ^0.7.0
  # flutter_slidable: ^3.0.1  # Not used in current implementation
  # shimmer: ^3.0.0  # Not used in current implementation
  
  # Charts and analytics
  fl_chart: ^0.65.0  # Compatible with Flutter 3.16+
  
  # Handwriting recognition
  google_ml_kit: ^0.20.0
  google_mlkit_text_recognition: ^0.15.0
  
  # Advanced file operations
  archive: ^4.0.7
  mime: ^2.0.0
  
  # State management
  provider: ^6.1.1
  
  # Local notifications
  flutter_local_notifications: ^18.0.0  # Compatible with Dart 3.5.4
  
  # Clipboard
  # flutter_clipboard: ^0.0.3  # Deprecated - using Flutter's built-in clipboard

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/models/
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf